In [1]:
import numpy as np

### Defining a scaler

In [2]:
s=5
print(s)

5


### Definig a vector

In [3]:
v1=[2,4,5,6]
print(v1)

[2, 4, 5, 6]


In [5]:
v2=np.array([2,4,6,8])
v2

array([2, 4, 6, 8])

### Defining a Row vector

In [6]:
rv=np.array([10,20,30,40])
rv

array([10, 20, 30, 40])

### Defining a column vector

In [8]:
cv=np.array([[2],[4],[6],[8]])
cv

array([[2],
       [4],
       [6],
       [8]])

# Defining a matrix

In [21]:
# Definie a 6*8 matrix of random integer values between 10 and 99

m=np.random.randint(10,100,6*8).reshape(6,8)
m

array([[52, 99, 69, 32, 61, 22, 70, 88],
       [27, 68, 53, 81, 28, 95, 82, 62],
       [77, 54, 59, 35, 16, 40, 32, 63],
       [91, 39, 16, 92, 26, 80, 60, 79],
       [77, 58, 21, 55, 20, 68, 99, 65],
       [90, 94, 51, 36, 99, 55, 35, 74]])

In [13]:
m.shape

(2, 5)

### Defining a diagonal matrix

In [15]:
# Define a diagonal matrix where the digaonal elements are 2,4,6,8

np.diag([2,4,6,8])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

# Scaler addtion, subtraction, multiplication and division with a vector

In [24]:
v=np.array([2,9,4,7])
s=2
v

array([2, 9, 4, 7])

In [25]:
v+s

array([ 4, 11,  6,  9])

In [26]:
v=np.array([[2],[9],[4],[7]])
s=2
v

array([[2],
       [9],
       [4],
       [7]])

In [27]:
v+s

array([[ 4],
       [11],
       [ 6],
       [ 9]])

In [28]:
v

array([[2],
       [9],
       [4],
       [7]])

In [29]:
v-5

array([[-3],
       [ 4],
       [-1],
       [ 2]])

In [30]:
v

array([[2],
       [9],
       [4],
       [7]])

In [31]:
v*2

array([[ 4],
       [18],
       [ 8],
       [14]])

In [32]:
v

array([[2],
       [9],
       [4],
       [7]])

In [33]:
v/2

array([[1. ],
       [4.5],
       [2. ],
       [3.5]])

# Scaler addtion, subtraction, multiplication and division with a Matrix

In [34]:
A=np.array([[2,4],[6,8]])
A

array([[2, 4],
       [6, 8]])

In [35]:
A+2

array([[ 4,  6],
       [ 8, 10]])

In [36]:
A-3

array([[-1,  1],
       [ 3,  5]])

In [37]:
A*3

array([[ 6, 12],
       [18, 24]])

# Vector with Vector- Addition, Subtraction and Division

In [40]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])

print(a)
print(b)

[1 2 3 4]
[2 4 6 8]


In [41]:
a+b

array([ 3,  6,  9, 12])

In [42]:
a-b

array([-1, -2, -3, -4])

In [43]:
b-a

array([1, 2, 3, 4])

In [44]:
a*b

array([ 2,  8, 18, 32])

# Matrix with Matrix- Addition, Subtraction and Division

In [52]:
A=np.array([[2,4],[6,8],[3,4],[5,6]])
A

array([[2, 4],
       [6, 8],
       [3, 4],
       [5, 6]])

In [57]:
B=np.array([[1,2],[4,6],[4,1],[3,5]])
B

array([[1, 2],
       [4, 6],
       [4, 1],
       [3, 5]])

In [58]:
A+B

array([[ 3,  6],
       [10, 14],
       [ 7,  5],
       [ 8, 11]])

In [59]:
A-B

array([[ 1,  2],
       [ 2,  2],
       [-1,  3],
       [ 2,  1]])

In [60]:
A/B

array([[2.        , 2.        ],
       [1.5       , 1.33333333],
       [0.75      , 4.        ],
       [1.66666667, 1.2       ]])

# Dot Product

### Vector with Vector dot product

In [62]:
a=np.array([1,2,3,4])
b=np.array([4,7,3,5])
a

array([1, 2, 3, 4])

In [63]:
b

array([4, 7, 3, 5])

In [64]:
np.dot(a,b)

47

In [66]:
[1*4 + 2*7 + 3*3 + 4*5]

[47]

### Matrix with vector dot product

In [70]:
A=np.array([[3,1],[5,2]])
A

array([[3, 1],
       [5, 2]])

In [71]:
a=np.array([[2],[4]])
a

array([[2],
       [4]])

In [72]:
np.dot(A,a)

array([[10],
       [18]])

In [73]:
A

array([[3, 1],
       [5, 2]])

In [75]:
a=np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [76]:
np.dot(A,a)

ValueError: shapes (2,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)

In [77]:
A.shape

(2, 2)

In [78]:
len(a)

3

### Matrix with matrix dot product

In [81]:
A=np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
B=np.array([1,5,3,6,4,2]).reshape(3,2)
B

array([[1, 5],
       [3, 6],
       [4, 2]])

In [84]:
A.shape

(3, 3)

In [85]:
B.shape

(3, 2)

In [86]:
np.dot(A,B)

array([[ 19,  23],
       [ 43,  62],
       [ 67, 101]])

In [87]:
A@B

array([[ 19,  23],
       [ 43,  62],
       [ 67, 101]])

In [88]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
B=np.array([1,2,3,4]).reshape(2,2)
B

array([[1, 2],
       [3, 4]])

In [91]:
A.shape

(3, 3)

In [92]:
B.shape

(2, 2)

In [93]:
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

# Properties of Dot Product

In [97]:
# For vectors (a,b)
# a.b=b.a

In [100]:
a=np.array([1,2,3,4])
b=np.array([5,3,4,1])

a@b,b@a

(27, 27)

In [105]:
# For vectors (a,b,c)
# a.(b+c)=a.b+a.c

a=np.array([1,2,3,4])
b=np.array([5,3,4,1])
c=np.array([3,1,8,6])

a@(b+c),a@b+a@c

(80, 80)

In [118]:
# For metrices (A,B)
# A.B != B.A
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
B=np.array([[1,2],[4,6],[3,2]])
B

array([[1, 2],
       [4, 6],
       [3, 2]])

In [111]:
A.shape

(3, 3)

In [112]:
B.shape

(3, 2)

In [114]:
A@B

array([[18, 20],
       [42, 50],
       [66, 80]])

In [115]:
B.shape

(3, 2)

In [116]:
A.shape

(3, 3)

In [117]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [119]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,2],[1,9]])
C=np.array([[3,7],[5,4]])

In [120]:
# A.(B+C)=A.B+A.C

In [122]:
A@B,B@A

(array([[ 7, 20],
        [19, 42]]),
 array([[11, 18],
        [28, 38]]))

In [124]:
A@(B+C)

array([[20, 35],
       [48, 79]])

In [126]:
A@B+A@C

array([[20, 35],
       [48, 79]])

In [94]:
# Transpose
# Determinant
# Inverse of a Matrix

In [95]:
# 2:35 

# Inverse of a Matrix

In [1]:
import numpy as np

In [2]:
# np.linalg.inv(arr)

In [3]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Determinant of a Matrix

In [5]:
np.linalg.det(arr)

In [8]:
np.round(np.linalg.det(A))

-2.0

In [9]:
# x+2y=10
# 2x+2y=20

In [10]:
A=np.array([[1,2],[2,2]])
A

array([[1, 2],
       [2, 2]])

In [11]:
b=np.array([[10],[20]])
b

array([[10],
       [20]])

In [14]:
X=np.linalg.inv(A)@b
X

array([[10.],
       [ 0.]])

In [15]:
X[0]

array([10.])

In [16]:
X[1]

array([0.])

In [17]:
A=np.array([[1,2,3],[2,1,1],[1,2,2]])
A

array([[1, 2, 3],
       [2, 1, 1],
       [1, 2, 2]])

In [19]:
np.round(np.linalg.det(A))

3.0

In [20]:
np.linalg.inv(A)

array([[ 0.        ,  0.66666667, -0.33333333],
       [-1.        , -0.33333333,  1.66666667],
       [ 1.        , -0.        , -1.        ]])